name: Deploy website to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
      - name: Install library
        run: |
          npm install
      - name: Build package
        run: |
          npm run build
      - name: Build documentation
        run: |
          npm run docs
      - name: Build demo application
        run: |
          cd demo
          npm install
          npm install .. --install-links
          npm run build
          cd ..
          cp -R docs demo/dist
      - name: Deploy website
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8  # v4.7.3
        with:
          folder: demo/dist
