name: Weekly main branch integration testing
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  integration-tests-curl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup node.js
        uses: actions/setup-node@v4
      - name: Install
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Prepare for testing
        run: |
          npm run test:setup-curl
      - name: Integration tests
        run: |
          npm run test:integration-curl
  integration-tests-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup node.js
        uses: actions/setup-node@v4
      - name: Install
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Prepare for testing
        run: |
          npm run test:setup-python
      - name: Integration tests
        run: |
          npm run test:integration-python
  integration-tests-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup node.js
        uses: actions/setup-node@v4
      - name: Install
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Prepare for testing
        run: |
          npm run test:setup-javascript
      - name: Integration tests
        run: |
          npm run test:integration-javascript
  integration-tests-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup node.js
        uses: actions/setup-node@v4
      - name: Install
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
      - name: Prepare for testing
        run: |
          npm run test:setup-php
      - name: Integration tests
        run: |
          npm run test:integration-php
