name: Weekly main branch integration testing
on:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  integration-tests-curl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup node.js
        uses: actions/setup-node@v4
      - name: Install
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Prepare for testing
        run: |
          npm run test:setup
      - name: Integration tests
        run: |
          npm run test:integration-curl
  integration-tests-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup node.js
        uses: actions/setup-node@v4
      - name: Install
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Prepare for testing
        run: |
          npm run test:setup
      - name: Integration tests
        run: |
          npm run test:integration-python      
